name: "Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    environment: dev
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        working-directory: infra
        id: fmt
        run: terraform fmt -check

      - name: aws-test
        id: aws
        run: aws sts get-caller-identity

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color

      - name: s3 sync
        id: sync
        working-directory: html
        run: aws s3 sync . s3://test-infra-bucket-austin-1